version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes: 
      - mongodb-data:/data/db
    env_file:
      - ./env/.mongo.env

  web:
    build: ./
    container_name: web
    ports:
      - '3003:3000'
    depends_on:
      - redis
      - mongodb
    env_file:
      - ./env/.env

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - web



volumes:
  redis-data:
  mongodb-data: