apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # 추가
  hostPath:
    path: /data/mongodb
    type: DirectoryOrCreate
